<?php
define("WEBSITE_NAME", "Đồ Thờ Sơn Đồng");
define("TITLE_NAME", "Tên");
define("TITLE_POSTS", "Bài viết");
define("TITLE_ABOUT", "Về ");
define("TITLE_SEARCH", "Tìm kiếm");
define("TITLE_UPDATE", "Cập nhật");
define("TITLE_TAGS", "Thẻ ");
define("TITLE_ERROR", "LỖI");
define("TITLE_BULK_ACTIONS", "Thao tác");
define("TITLE_SELECT_BULK_ACTION", "Chọn thao tác");
define("TITLE_SELECT", "Chọn");
define("TITLE_DELETE", "Xóa");
define("TITLE_APPLY", "Áp dụng");
define("TITLE_ITEMS", "đối tượng");
define("TITLE_CURRENT_PAGE", "Trang hiện tại");
define("TITLE_OF", "của");
define("TITLE_FIRST_PAGE", "Trang đầu tiên");
define("TITLE_PREVIOUS_PAGE", "Trang trước đấy");
define("TITLE_NEXT_PAGE", "Trang tiếp theo");
define("TITLE_LAST_PAGE", "Trang cuối cùng");
define("TITLE_SELECT_ALL", "Chọn tất cả");
define("TITLE_SHOW_MORE_DETAILS", "Xem chi tiết");
define("TITLE_CHANGE", "Đổi");
define("TITLE_SLUG", "Viết tắt");
define("TITLE_LEVEL", "Mức");
define("TITLE_PARENT", "Cha");
define("TITLE_DESCRIPTION", "Mô tả");
define("TITLE_IMAGES", "Ảnh");
define("TITLE_HIDE", "Ẩn");
define("TITLE_SHOW", "Hiện");
define("TITLE_CANCEL", "Hủy");
define("TITLE_COLUMNS", "Cột");
define("TITLE_PAGINATION", "Phân trang");
define("TITLE_NUMBER_OF_ITEMS_PER_PAGE", "Số lượng đối tượng trên một trang:");
define("TITLE_NONE", "Không");
define("TITLE_BACK_TO", "Trở lại");
define("TITLE_ADD_NEW", "Thêm mới");
define("TITLE_ALL", "Tất cả");
define("TITLE_EDIT", "Sửa");
define("TITLE_VIEW", "Xem");
define("TITLE_REQUIRED", "(*)");
define("DESC_TYPE_IMAGE_REQUIRED", "(cần sử dụng định dạng .jpg, .pgn, .jpeg)");
define("CONFIRM_DELETE_CANCEL_OK", ". \\n \"Hủy\" để dừng lại, \"OK\" để xóa.");
define("CONFIRM_ACTION_CANCEL_OK", ". \\n \"Hủy\" để dùng lại, \"OK\" để thực thi hành động này.");
define("CONFIRM_EDIT_INFO_CANCEL_OK", ". \\n \"Hủy\" để dừng lại, \"OK\" để sửa.");
define("CONFIRM_DELETE_IMAGE", "Bạn có thực sự muốn xóa ảnh này không. ");
define("DEFAULT_KEYWORD", "do tho tuong phat, đồ thờ tượng phật, làng nghề sơn đồng, do tho son dong, đồ thờ sơn đồng, tượng phật sơn đồng");
define("DEFAULT_DESCRIPTION_WEBSITE", "Cơ sở sản xuất Đồ thờ tượng phật Hiệp Thủy chuyên Tư vấn, thiết kế đình, chùa, nhà thờ, gian thờ tại nhà riêng... Làm mới, tu sửa đồ thờ cúng, tượng phật.");
define("DEFAULT_TITLE_WEBSITE", "Đồ thờ tượng phật Hiệp Thủy – Sản phẩm của Làng nghề Sơn Đồng");
define("DEFAULT_GEO_REGION", "VN-HN");
define("DEFAULT_GEO_POSITION", "21.046894, 105.704036");
define("DEFAULT_SITE_NAME", "Xưởng sản xuất Đồ thờ - Tượng phật HIỆP THỦY");
define("DEFAULT_PHONE", "04. 30 000 000");
define("DEFAULT_PHONE_VALUE", "0430000000");
define("DEFAULT_PHONE_2", "098 000 000");
define("DEFAULT_PHONE_VALUE_2", "+8498000000");
define("DEFAULT_ADDRESS", "Ngã tư Sơn Đồng - Hoài Đức - Hà Nội");
define("DEFAULT_EMAIL", "dothohiepthuy@gmail.com");
define("DEFAULT_MAP_TITLE", "Đồ thờ Hiệp Thủy, Ngã tư Sơn Đồng, Hoài Đức, Hà Nội, Việt Nam");

define("TITLE_DETAIL_IMAGE", "Chi tiết hình ảnh");
define("TITLE_INDEX_IMAGE", "Ảnh mẫu số");
define("TITLE_ADDRESS", "Địa chỉ");
define("TITLE_HOTLINE", "Hotline");
define("TITLE_PHONE", "Điện thoại");


define("USER_ERROR_NAME_EMPTY", "Trường tên rỗng");
define("USER_ERROR_SLUG_EMPTY", "Viết tắt trống");
define("USER_ERROR_PARENT_NOT_IMPOSSIBLE", "Mức cha không hợp lệ");
define("USER_ERROR_SLUG_EXISTED", "Viết tắt đã tồn tại");
define("USER_ERROR_NAME_EXISTED", "Tên đã tồn tại");