<?php
define("WEBSITE_NAME", "Đồ Thờ Sơn Đồng");
define("TITLE_NAME", "Name");
define("TITLE_POSTS", "Posts");
define("TITLE_ABOUT", "About ");
define("TITLE_SEARCH", "Search");
define("TITLE_UPDATE", "Update");
define("TITLE_TAGS", "Tags ");
define("TITLE_ERROR", "ERROR");
define("TITLE_BULK_ACTIONS", "Bulk Actions");
define("TITLE_SELECT_BULK_ACTION", "Select bulk action");
define("TITLE_SELECT", "Select");
define("TITLE_DELETE", "Delete");
define("TITLE_APPLY", "Apply");
define("TITLE_ITEMS", "items");
define("TITLE_CURRENT_PAGE", "Current Page");
define("TITLE_OF", "of");
define("TITLE_FIRST_PAGE", "First Page");
define("TITLE_PREVIOUS_PAGE", "Previous page");
define("TITLE_NEXT_PAGE", "Next page");
define("TITLE_LAST_PAGE", "Last page");
define("TITLE_SELECT_ALL", "Select All");
define("TITLE_SHOW_MORE_DETAILS", "Show more details");
define("TITLE_CHANGE", "Change");
define("TITLE_SLUG", "Slug");
define("TITLE_LEVEL", "Level");
define("TITLE_PARENT", "Parent");
define("TITLE_DESCRIPTION", "Description");
define("TITLE_IMAGES", "Images");
define("TITLE_HIDE", "Hide");
define("TITLE_SHOW", "Show");
define("TITLE_CANCEL", "Cancel");
define("TITLE_COLUMNS", "Columns");
define("TITLE_PAGINATION", "Pagination");
define("TITLE_NUMBER_OF_ITEMS_PER_PAGE", "Number of items per page:");
define("TITLE_NONE", "None");
define("TITLE_BACK_TO", "Back to");
define("TITLE_ADD_NEW", "Add New");
define("TITLE_ALL", "All");
define("TITLE_EDIT", "Edit");
define("TITLE_VIEW", "View");
define("TITLE_REQUIRED", "(required)");
define("DESC_TYPE_IMAGE_REQUIRED", "(required .jpg, .pgn, .jpeg)");
define("CONFIRM_DELETE_CANCEL_OK", ". \\n \"Cancel\" to stop, \"OK\" to delete.");
define("CONFIRM_ACTION_CANCEL_OK", ". \\n \"Cancel\" to stop, \"OK\" to execute this action.");
define("CONFIRM_EDIT_INFO_CANCEL_OK", ". \\n \"Cancel\" to stop, \"OK\" to edit.");
define("CONFIRM_DELETE_IMAGE", "You are about to permanently delete these image. ");
define("DEFAULT_KEYWORD", "do tho tuong phat, đồ thờ tượng phật, làng nghề sơn đồng, do tho son dong, đồ thờ sơn đồng, tượng phật sơn đồng");
define("DEFAULT_DESCRIPTION_WEBSITE", "Cơ sở sản xuất Đồ thờ tượng phật Hiệp Thủy chuyên Tư vấn, thiết kế đình, chùa, nhà thờ, gian thờ tại nhà riêng... Làm mới, tu sửa đồ thờ cúng, tượng phật.");
define("DEFAULT_TITLE_WEBSITE", "Đồ thờ tượng phật Hiệp Thủy – Sản phẩm của Làng nghề Sơn Đồng");
define("DEFAULT_GEO_REGION", "VN-HN");
define("DEFAULT_GEO_POSITION", "21.046894, 105.704036");
define("DEFAULT_SITE_NAME", "Xưởng sản xuất Đồ thờ - Tượng phật HIỆP THỦY");
define("DEFAULT_PHONE", "04. 30 000 000");
define("DEFAULT_PHONE_VALUE", "0430000000");
define("DEFAULT_PHONE_2", "098 000 000");
define("DEFAULT_PHONE_VALUE_2", "+8498000000");
define("DEFAULT_ADDRESS", "Ngã tư Sơn Đồng - Hoài Đức - Hà Nội");
define("DEFAULT_EMAIL", "dothohiepthuy@gmail.com");
define("DEFAULT_MAP_TITLE", "Đồ thờ Hiệp Thủy, Ngã tư Sơn Đồng, Hoài Đức, Hà Nội, Việt Nam");

define("TITLE_DETAIL_IMAGE", "Chi tiết hình ảnh");
define("TITLE_INDEX_IMAGE", "Ảnh mẫu số");
define("TITLE_ADDRESS", "Địa chỉ");
define("TITLE_HOTLINE", "Hotline");
define("TITLE_PHONE", "Điện thoại");


define("USER_ERROR_NAME_EMPTY", "Name is empty");
define("USER_ERROR_SLUG_EMPTY", "Slug is empty");
define("USER_ERROR_PARENT_NOT_IMPOSSIBLE", "Parent is not impossible");
define("USER_ERROR_SLUG_EXISTED", "Slug existed");
define("USER_ERROR_NAME_EXISTED", "Name existed");